[2022-07-21 00:55:53] [INFO    ] discord.client: logging in using static token
[2022-07-21 00:55:56] [INFO    ] discord.gateway: Shard ID None has sent the IDENTIFY payload.
[2022-07-21 00:55:56] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 244fca99b9cabe43f1a9129ad029b776).
[2022-07-21 00:55:58] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "/home/runner/testing/venv/lib/python3.8/site-packages/discord/client.py", line 456, in _run_event
    await coro(*args, **kwargs)
  File "/home/runner/testing/cogs/Misc.py", line 62, in on_ready
    self.bot.launch_time = datetime.datetime.utcnow()
NameError: name 'datetime' is not defined
[2022-07-21 02:37:48] [INFO    ] discord.client: Got a request to RESUME the websocket.
[2022-07-21 02:37:48] [INFO    ] discord.gateway: Shard ID None has sent the RESUME payload.
[2022-07-21 02:37:48] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 244fca99b9cabe43f1a9129ad029b776.
